# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '总模板.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1330, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QLabel(self.frame_6)
        self.label_1.setEnabled(False)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_9.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.frame_6)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_4)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_3)
        self.label_31 = QtWidgets.QLabel(self.frame_6)
        self.label_31.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_7.addWidget(self.label_31)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setMinimumSize(QtCore.QSize(100, 0))
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_7.addWidget(self.checkBox_4)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_8.addWidget(self.spinBox_5)
        self.label_41 = QtWidgets.QLabel(self.frame_6)
        self.label_41.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_8.addWidget(self.label_41)
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_8.addWidget(self.spinBox_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setMinimumSize(QtCore.QSize(100, 0))
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_8.addWidget(self.checkBox_3)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_21.setEnabled(False)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_2.addWidget(self.checkBox_21, 1, 0, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_41.setEnabled(False)
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout_2.addWidget(self.checkBox_41, 3, 0, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_33.setEnabled(False)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_2.addWidget(self.checkBox_33, 2, 2, 1, 1)
        self.checkBox_43 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_43.setEnabled(False)
        self.checkBox_43.setObjectName("checkBox_43")
        self.gridLayout_2.addWidget(self.checkBox_43, 3, 2, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_13.setEnabled(False)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_2.addWidget(self.checkBox_13, 0, 2, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_31.setEnabled(False)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_2.addWidget(self.checkBox_31, 2, 0, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_22.setEnabled(False)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_2.addWidget(self.checkBox_22, 1, 1, 1, 1)
        self.checkBox_42 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_42.setEnabled(False)
        self.checkBox_42.setObjectName("checkBox_42")
        self.gridLayout_2.addWidget(self.checkBox_42, 3, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_23.setEnabled(False)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_2.addWidget(self.checkBox_23, 1, 2, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_32.setEnabled(False)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_2.addWidget(self.checkBox_32, 2, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton.setEnabled(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 0, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 0, 1, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_51.setEnabled(False)
        self.checkBox_51.setObjectName("checkBox_51")
        self.gridLayout_2.addWidget(self.checkBox_51, 4, 0, 1, 1)
        self.checkBox_52 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_52.setEnabled(False)
        self.checkBox_52.setObjectName("checkBox_52")
        self.gridLayout_2.addWidget(self.checkBox_52, 4, 1, 1, 1)
        self.checkBox_53 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_53.setEnabled(False)
        self.checkBox_53.setObjectName("checkBox_53")
        self.gridLayout_2.addWidget(self.checkBox_53, 4, 2, 1, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_6)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_13.addWidget(self.dateEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.label_61 = QtWidgets.QLabel(self.frame_6)
        self.label_61.setEnabled(False)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_13.addWidget(self.label_61)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_6)
        self.dateEdit_2.setEnabled(False)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_13.addWidget(self.dateEdit_2)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_8)
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.spinBox_9 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_9.setEnabled(False)
        self.spinBox_9.setMinimum(1)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_14.addWidget(self.spinBox_9)
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        self.spinBox_10 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_10.setEnabled(False)
        self.spinBox_10.setMinimum(1)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_14.addWidget(self.spinBox_10)
        self.label_23 = QtWidgets.QLabel(self.frame_6)
        self.label_23.setEnabled(False)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setChecked(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_14.addWidget(self.checkBox_6)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.verticalLayout_5.addWidget(self.textBrowser_1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_12.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_12.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_12.addWidget(self.pushButton_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        # self.tableView = QtWidgets.QTableView(self.frame_2)
        # self.tableView.setObjectName("tableView")
        # self.horizontalLayout_3.addWidget(self.tableView)
        self.verticalLayout.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.progressBar_3 = QtWidgets.QProgressBar(self.frame_3)
        self.progressBar_3.setMaximum(100)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.horizontalLayout_10.addWidget(self.progressBar_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_2.addWidget(self.textBrowser_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        spacerItem11 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1330, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_4)
        self.menu_3.addAction(self.action_2)
        self.menu_3.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "text"))
        self.label_1.setText(_translate("MainWindow", "关键字："))
        self.comboBox.setItemText(0, _translate("MainWindow", "test"))
        self.label_2.setText(_translate("MainWindow", "爬取规则："))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "不限"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "不限"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "不限"))
        self.label_3.setText(_translate("MainWindow", "价格区间："))
        self.label_31.setText(_translate("MainWindow", "至"))
        self.checkBox_4.setText(_translate("MainWindow", "不限"))
        self.label_4.setText(_translate("MainWindow", "搜索页数："))
        self.label_41.setText(_translate("MainWindow", "至 "))
        self.checkBox_3.setText(_translate("MainWindow", "全部"))
        self.label_5.setText(_translate("MainWindow", "多选框："))
        self.checkBox_21.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_41.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_33.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_43.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_13.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_31.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_22.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_42.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_23.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_32.setText(_translate("MainWindow", "checkbox"))
        self.radioButton.setText(_translate("MainWindow", "全选"))
        self.checkBox_12.setText(_translate("MainWindow", "checkbox"))
        self.checkBox_51.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_52.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_53.setText(_translate("MainWindow", "CheckBox"))
        self.label_6.setText(_translate("MainWindow", "日期："))
        self.label_61.setText(_translate("MainWindow", "至"))
        self.label_7.setText(_translate("MainWindow", "导入文件："))
        self.pushButton_8.setText(_translate("MainWindow", "点击选择"))
        self.label.setText(_translate("MainWindow", "数据位置："))
        self.label_21.setText(_translate("MainWindow", "第"))
        self.label_22.setText(_translate("MainWindow", "个表格，第"))
        self.label_23.setText(_translate("MainWindow", "列。"))
        self.checkBox_6.setText(_translate("MainWindow", "含第一行"))
        self.pushButton_1.setText(_translate("MainWindow", "检查参数"))
        self.pushButton_2.setText(_translate("MainWindow", "清空参数"))
        self.pushButton_3.setText(_translate("MainWindow", "清空提示窗口"))
        self.label_12.setText(_translate("MainWindow", "当前状态："))
        self.label_13.setText(_translate("MainWindow", "参数设置中"))
        self.label_15.setText(_translate("MainWindow", "爬取进度："))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "开始"))
        self.pushButton_5.setText(_translate("MainWindow", "中止"))
        self.pushButton_6.setText(_translate("MainWindow", "导出至Excel"))
        self.menu.setTitle(_translate("MainWindow", "数据库"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "连接数据库（待开发）"))
        self.action_2.setText(_translate("MainWindow", "版本"))
        self.action_3.setText(_translate("MainWindow", "制作人"))
        self.action_4.setText(_translate("MainWindow", "联系我们"))

