# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OGweibobangdan.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_13.setObjectName("radioButton_13")
        self.gridLayout.addWidget(self.radioButton_13, 3, 1, 1, 1)
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout.addWidget(self.radioButton_15, 4, 1, 1, 1)
        self.radioButton_46 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_46.setObjectName("radioButton_46")
        self.gridLayout.addWidget(self.radioButton_46, 0, 1, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout.addWidget(self.radioButton_8, 9, 0, 1, 1)
        self.radioButton_40 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_40.setObjectName("radioButton_40")
        self.gridLayout.addWidget(self.radioButton_40, 1, 0, 1, 1)
        self.radioButton_50 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_50.setObjectName("radioButton_50")
        self.gridLayout.addWidget(self.radioButton_50, 15, 1, 1, 1)
        self.radioButton_47 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_47.setObjectName("radioButton_47")
        self.gridLayout.addWidget(self.radioButton_47, 1, 1, 1, 1)
        self.radioButton_42 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_42.setObjectName("radioButton_42")
        self.gridLayout.addWidget(self.radioButton_42, 14, 0, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout.addWidget(self.radioButton_17, 6, 1, 1, 1)
        self.radioButton_48 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_48.setObjectName("radioButton_48")
        self.gridLayout.addWidget(self.radioButton_48, 13, 1, 1, 1)
        self.radioButton_41 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_41.setObjectName("radioButton_41")
        self.gridLayout.addWidget(self.radioButton_41, 13, 0, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout.addWidget(self.radioButton_16, 5, 1, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout.addWidget(self.radioButton_7, 6, 0, 1, 1)
        self.radioButton_39 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_39.setObjectName("radioButton_39")
        self.gridLayout.addWidget(self.radioButton_39, 0, 0, 1, 1)
        self.radioButton_22 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_22.setObjectName("radioButton_22")
        self.gridLayout.addWidget(self.radioButton_22, 12, 1, 1, 1)
        self.radioButton_45 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_45.setObjectName("radioButton_45")
        self.gridLayout.addWidget(self.radioButton_45, 17, 0, 1, 1)
        self.radioButton_52 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_52.setObjectName("radioButton_52")
        self.gridLayout.addWidget(self.radioButton_52, 17, 1, 1, 1)
        self.radioButton_51 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_51.setObjectName("radioButton_51")
        self.gridLayout.addWidget(self.radioButton_51, 16, 1, 1, 1)
        self.radioButton_44 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_44.setObjectName("radioButton_44")
        self.gridLayout.addWidget(self.radioButton_44, 16, 0, 1, 1)
        self.radioButton_20 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_20.setObjectName("radioButton_20")
        self.gridLayout.addWidget(self.radioButton_20, 10, 1, 1, 1)
        self.radioButton_49 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_49.setObjectName("radioButton_49")
        self.gridLayout.addWidget(self.radioButton_49, 14, 1, 1, 1)
        self.radioButton_43 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_43.setObjectName("radioButton_43")
        self.gridLayout.addWidget(self.radioButton_43, 15, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 3, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 2, 0, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout.addWidget(self.radioButton_12, 2, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout.addWidget(self.radioButton_10, 8, 0, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout.addWidget(self.radioButton_19, 9, 1, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout.addWidget(self.radioButton_6, 5, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 12, 0, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_14.setObjectName("radioButton_14")
        self.gridLayout.addWidget(self.radioButton_14, 7, 1, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_18.setObjectName("radioButton_18")
        self.gridLayout.addWidget(self.radioButton_18, 8, 1, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 10, 0, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout.addWidget(self.radioButton_9, 11, 0, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout.addWidget(self.radioButton_21, 11, 1, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout.addWidget(self.radioButton_11, 7, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.gridLayout.addLayout(self.horizontalLayout_7, 18, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.verticalLayout_5.addWidget(self.textBrowser_1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_4.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        # self.tableView = QtWidgets.QTableView(self.frame_2)
        # self.tableView.setObjectName("tableView")
        # self.horizontalLayout_3.addWidget(self.tableView)
        self.verticalLayout.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_2.addWidget(self.textBrowser_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        spacerItem2 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_4)
        self.menu_3.addAction(self.action_2)
        self.menu_3.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "微博榜单"))
        self.radioButton_13.setText(_translate("MainWindow", "旅游"))
        self.radioButton_15.setText(_translate("MainWindow", "育儿"))
        self.radioButton_46.setText(_translate("MainWindow", "情感"))
        self.radioButton_8.setText(_translate("MainWindow", "电视剧"))
        self.radioButton_40.setText(_translate("MainWindow", "新时达"))
        self.radioButton_50.setText(_translate("MainWindow", "生活记录"))
        self.radioButton_47.setText(_translate("MainWindow", "搞笑"))
        self.radioButton_42.setText(_translate("MainWindow", "运动健身"))
        self.radioButton_17.setText(_translate("MainWindow", "美食"))
        self.radioButton_48.setText(_translate("MainWindow", "动漫"))
        self.radioButton_41.setText(_translate("MainWindow", "体育"))
        self.radioButton_16.setText(_translate("MainWindow", "教育"))
        self.radioButton_7.setText(_translate("MainWindow", "财经"))
        self.radioButton_39.setText(_translate("MainWindow", "话题榜"))
        self.radioButton_22.setText(_translate("MainWindow", "时尚美妆"))
        self.radioButton_45.setText(_translate("MainWindow", "美图"))
        self.radioButton_52.setText(_translate("MainWindow", "其他"))
        self.radioButton_51.setText(_translate("MainWindow", "创意征集"))
        self.radioButton_44.setText(_translate("MainWindow", "军事"))
        self.radioButton_20.setText(_translate("MainWindow", "读书"))
        self.radioButton_49.setText(_translate("MainWindow", "萌宠"))
        self.radioButton_43.setText(_translate("MainWindow", "健康"))
        self.radioButton_3.setText(_translate("MainWindow", "互联网"))
        self.radioButton.setText(_translate("MainWindow", "社会"))
        self.radioButton_12.setText(_translate("MainWindow", "游戏"))
        self.radioButton_10.setText(_translate("MainWindow", "综艺"))
        self.radioButton_19.setText(_translate("MainWindow", "星座"))
        self.radioButton_6.setText(_translate("MainWindow", "数码"))
        self.radioButton_4.setText(_translate("MainWindow", "汽车"))
        self.radioButton_14.setText(_translate("MainWindow", "公益"))
        self.radioButton_18.setText(_translate("MainWindow", "房产"))
        self.radioButton_5.setText(_translate("MainWindow", "电影"))
        self.radioButton_9.setText(_translate("MainWindow", "音乐"))
        self.radioButton_21.setText(_translate("MainWindow", "艺术"))
        self.radioButton_11.setText(_translate("MainWindow", "明星"))
        self.radioButton_2.setText(_translate("MainWindow", "科普"))
        self.label_7.setText(_translate("MainWindow", "导出文件："))
        self.pushButton_10.setText(_translate("MainWindow", "点击选择"))
        self.pushButton_1.setText(_translate("MainWindow", "检查参数"))
        self.pushButton_2.setText(_translate("MainWindow", "清空参数"))
        self.pushButton_3.setText(_translate("MainWindow", "清空提示窗口"))
        self.pushButton_4.setText(_translate("MainWindow", "开始"))
        self.pushButton_5.setText(_translate("MainWindow", "中止"))
        self.pushButton_6.setText(_translate("MainWindow", "导入至Excel"))
        self.menu.setTitle(_translate("MainWindow", "数据库"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "连接数据库（待开发）"))
        self.action_2.setText(_translate("MainWindow", "版本"))
        self.action_3.setText(_translate("MainWindow", "制作人"))
        self.action_4.setText(_translate("MainWindow", "联系我们"))

